version: '3.8'

services:
  code_exec:
    build:
      context: ./code_exec
    image: soul4927/s-talk_code_exec:latest # 빌드 이미지 이름 , pull할때도 사용
    ports:
      - '8081:8081'
    networks:
      - mynet

  # fetch:
  #   build:
  #     context: ./fetch
  #   ports:
  #     - '8001:8001'
  #   networks:
  #     - mynet

  llm:
    build:
      context: ./llm
    image: soul4927/s-talk_llm:latest
    ports:
      - '8080:8080'
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
